class Mot {
    constructor(fr, jp, score)
    {
        this.fr = fr;
        this.jp = jp;
        this.score = score;
        this.counter = 0;
    }

    getPercentage()
    {
        return this.counter === 0 ? -1 : this.score
    }
}

export const vocabulaire = [
    new Mot(['bleu'],'あおい',0),
    new Mot(['rouge'],'あかい',0),
    new Mot(['automne'],'あき',0),
    new Mot(['ouvrir'],'あける',0),
    new Mot(['donner'],'あげる',0),
    new Mot(['matin'],'あさ',0),
    new Mot(['petit-déjeuner'],'あさごはん',0),
    new Mot(['après-demain'],'あさって',0),
    new Mot(['pied', 'jambe'],'あし',0),
    new Mot(['demain'],'あした',0),
    new Mot(['jouer'],'あそぶ',0),
    new Mot(['tête'],'あたま',0),
    new Mot(['nouveau'],'あたらしい',0),
    new Mot(['chaud'],'あつい',0),
    new Mot(['grand-frère'],'あに',0),
    new Mot(['grande-soeur'],'あね',0),
    new Mot(['appartement'],'アパート',0),
    new Mot(['dangereux'],'あぶない',0),
    new Mot(['sucré'],'あまい',0),
    new Mot(['pluie'],'あめ',0),
    new Mot(['laver'],'あらう',0),
    new Mot(['marcher'],'あるく',0),
    new Mot(['non'],'いいえ',0),
    new Mot(['dire'],'いう',0),
    new Mot(['maison'],'いえ',0),
    new Mot(['aller'],'いく',0),
    new Mot(['médecin', 'docteur'],'いしゃ',0),
    new Mot(['chaise'],'いす',0),
    new Mot(['occupé'],'いそがしい',0),
    new Mot(['un'],'いち',0),
    new Mot(['chien'],'いぬ',0),
    new Mot(['maintenant'],'いま',0),
    new Mot(['petite-soeur'],'いもうと',0),
    new Mot(['entrée'],'いりぐち',0),
    new Mot(['couleur'],'いろ',0),
    new Mot(['dessus', 'au-dessus'],'うえ',0),
    new Mot(['derrière'],'うしろ',0),
    new Mot(['chanson'],'うた',0),
    new Mot(['chanter'],'うたう',0),
    new Mot(['mer'],'うみ',0),
    new Mot(['vendre'],'うる',0),
    new Mot(['manteau'],'うわぎ',0),
    new Mot(['image'],'え',0),
    new Mot(['film'],'えいが',0),
    new Mot(['cinéma'],'えいがかん',0),
    new Mot(['anglais'],'えいご',0),
    new Mot(['gare'],'えき',0),
    new Mot(['ascenseur'],'エレベーター',0),
    new Mot(['yen'],'えん',0),
    new Mot(['délicieux'],'おいしい',0),
    new Mot(['grand', 'gros'],'おおきい',0),
    new Mot(['argent'],'おかね',0),
    new Mot(['thé'],'おちゃ',0),
    new Mot(['toilettes'],'おてあらい',0),
    new Mot(['petit-frère'],'おとうと',0),
    new Mot(['homme'],'おとこ',0),
    new Mot(['avant-hier'],'おととい',0),
    new Mot(['adulte'],'おとな ',0),
    new Mot(['nager'],'およぐ',0),
    new Mot(['finir'],'おわる',0),
    new Mot(['musique'],'おんがく',0),
    new Mot(['femme'],'おんな',0),
    new Mot(['étranger'],'がいこくじん',0),
    new Mot(['entreprise'],'かいしゃ',0),
    new Mot(['escalier'],'かいだん',0),
    new Mot(['acheter'],'かう ',0),
    new Mot(['visage'],'かお',0),
    new Mot(['clé'],'かぎ',0),
    new Mot(['écrire'],'かく ',0),
    new Mot(['parapluie'],'かさ',0),
    new Mot(['prêter'],'かす',0),
    new Mot(['vent'],'かぜ ',0),
    new Mot(['famille'],'かぞく',0),
    new Mot(['école'],'がっこう',0),
    new Mot(['sac'],'かばん',0),
    new Mot(['papier'],'かみ',0),
    new Mot(['appareil photo'],'カメラ',0),
    new Mot(['mardi'],'かようび ',0),
    new Mot(['épicé'],'からい',0),
    new Mot(['emprunter'],'かりる',0),
    new Mot(['léger'],'かるい',0),
    new Mot(['calendrier'],'カレンダー',0),
    new Mot(['rivière'],'かわ',0),
    new Mot(['mignon'],'かわいい',0),
    new Mot(['arbre'],'き',0),
    new Mot(['jaune'],'きいろい',0),
    new Mot(['écouter'],'きく',0),
    new Mot(['nord'],'きた',0),
    new Mot(['guitare'],'ギター',0),
    new Mot(['sale'],'きたない',0),
    new Mot(['timbre'],'きって',0),
    new Mot(['ticket'],'きっぷ',0),
    new Mot(['hier'],'きのう',0),
    new Mot(['neuf'],'きゅう',0),
    new Mot(['aujourd\'hui'],'きょう',0),
    new Mot(['salle de classe'],'きょうしつ',0),
    new Mot(['année dernière'],'きょねん',0),
    new Mot(['beau'],'きれい',0),
    new Mot(['banque'],'ぎんこう',0),
    new Mot(['vendredi'],'きんようび',0),
    new Mot(['médicament'],'くすり',0),
    new Mot(['fruit'],'きくだもの',0),
    new Mot(['bouche', 'ouverture'],'くち',0),
    new Mot(['chaussures'],'くつ',0),
    new Mot(['chaussettes'],'くつした',0),
    new Mot(['pays'],'くに',0),
    new Mot(['voiture', 'automobile'],'くるま',0),
    new Mot(['noir'],'くろい',0),
    new Mot(['ce matin'],'けさ',0),
    new Mot(['mariage'],'けっこん',0),
    new Mot(['entrée', 'vestibule'],'げんかん',0),
    new Mot(['cinq'],'ご',0),
    new Mot(['parc'],'こうえん',0),
    new Mot(['thé noir'],'こうちゃ',0),
    new Mot(['voix'],'こえ',0),
    new Mot(['café'],'コーヒー',0),
    new Mot(['après-midi'],'ごご',0),
    new Mot(['matin'],'ごぜん',0),
    new Mot(['cette année'],'ことし',0),
    new Mot(['mot'],'ことば',0),
    new Mot(['enfant'],'こども',0),
    new Mot(['repas'],'ごはん',0),
    new Mot(['ce mois', 'ce mois-ci'],'こんげつ',0),
    new Mot(['cette semaine'],'こんしゅう',0),
    new Mot(['bonjour'],'こんにちは',0),
    new Mot(['ce soir'],'こんばん',0),
    new Mot(['bonsoir'],'こんばんは',0),
    new Mot(['poisson'],'さかな',0),
    new Mot(['alcool'],'さけ',0),
    new Mot(['magazine', 'revue'],'ざっし',0),
    new Mot(['sucre'],'さとう',0),
    new Mot(['froid'],'さむい',0),
    new Mot(['au revoir'],'さようなら',0),
    new Mot(['assiette'],'さら',0),
    new Mot(['trois', 'monsieur', 'madame'],'さん',0),
    new Mot(['promenade', 'balade'],'さんぽ',0),
    new Mot(['quatre'],'し',0),
    new Mot(['heure'],'じ',0),
    new Mot(['sel'],'しお',0),
    new Mot(['mais', 'cependant'],'しかし',0),
    new Mot(['travail'],'しごと',0),
    new Mot(['chat'],'ねこ',0),
    new Mot(['souris'],'ねずみ',0)
]