class Mot {
    constructor(fr, jp, score)
    {
        this.fr = fr;
        this.jp = jp;
        this.score = score;
        this.counter = 0;
    }

    getPercentage()
    {
        return this.counter === 0 ? -1 : this.score
    }
}

const basic_score = 15625

export const vocabulaire = [
    new Mot(['bleu'],'あおい',basic_score),
    new Mot(['rouge'],'あかい',basic_score),
    new Mot(['automne'],'あき',basic_score),
    new Mot(['ouvrir'],'あける',basic_score),
    new Mot(['donner', 'offrir'],'あげる',basic_score),
    new Mot(['matin'],'あさ',basic_score),
    new Mot(['petit-déjeuner'],'あさごはん',basic_score),
    new Mot(['après-demain'],'あさって',basic_score),
    new Mot(['pied', 'jambe'],'あし',basic_score),
    new Mot(['demain'],'あした',basic_score),
    new Mot(['jouer'],'あそぶ',basic_score),
    new Mot(['tête'],'あたま',basic_score),
    new Mot(['nouveau'],'あたらしい',basic_score),
    new Mot(['chaud'],'あつい',basic_score),
    new Mot(['grand-frère'],'あに',basic_score),
    new Mot(['grande-soeur'],'あね',basic_score),
    new Mot(['appartement'],'アパート',basic_score),
    new Mot(['dangereux'],'あぶない',basic_score),
    new Mot(['sucré'],'あまい',basic_score),
    new Mot(['pluie'],'あめ',basic_score),
    new Mot(['laver'],'あらう',basic_score),
    new Mot(['marcher'],'あるく',basic_score),
    new Mot(['non'],'いいえ',basic_score),
    new Mot(['dire'],'いう',basic_score),
    new Mot(['maison'],'いえ',basic_score),
    new Mot(['aller'],'いく',basic_score),
    new Mot(['médecin', 'docteur'],'いしゃ',basic_score),
    new Mot(['chaise'],'いす',basic_score),
    new Mot(['occupé'],'いそがしい',basic_score),
    new Mot(['un'],'いち',basic_score),
    new Mot(['chien'],'いぬ',basic_score),
    new Mot(['maintenant'],'いま',basic_score),
    new Mot(['petite-soeur'],'いもうと',basic_score),
    new Mot(['entrée'],'いりぐち',basic_score),
    new Mot(['couleur'],'いろ',basic_score),
    new Mot(['dessus', 'au-dessus'],'うえ',basic_score),
    new Mot(['derrière'],'うしろ',basic_score),
    new Mot(['chanson'],'うた',basic_score),
    new Mot(['chanter'],'うたう',basic_score),
    new Mot(['mer'],'うみ',basic_score),
    new Mot(['vendre'],'うる',basic_score),
    new Mot(['manteau'],'うわぎ',basic_score),
    new Mot(['image'],'え',basic_score),
    new Mot(['film'],'えいが',basic_score),
    new Mot(['cinéma'],'えいがかん',basic_score),
    new Mot(['anglais'],'えいご',basic_score),
    new Mot(['gare'],'えき',basic_score),
    new Mot(['ascenseur'],'エレベーター',basic_score),
    new Mot(['yen'],'えん',basic_score),
    new Mot(['délicieux'],'おいしい',basic_score),
    new Mot(['grand', 'gros'],'おおきい',basic_score),
    new Mot(['argent'],'おかね',basic_score),
    new Mot(['thé'],'おちゃ',basic_score),
    new Mot(['toilettes'],'おてあらい',basic_score),
    new Mot(['petit-frère'],'おとうと',basic_score),
    new Mot(['homme'],'おとこ',basic_score),
    new Mot(['avant-hier'],'おととい',basic_score),
    new Mot(['adulte'],'おとな ',basic_score),
    new Mot(['nager'],'およぐ',basic_score),
    new Mot(['finir'],'おわる',basic_score),
    new Mot(['musique'],'おんがく',basic_score),
    new Mot(['femme'],'おんな',basic_score),
    new Mot(['étranger'],'がいこくじん',basic_score),
    new Mot(['entreprise'],'かいしゃ',basic_score),
    new Mot(['escalier'],'かいだん',basic_score),
    new Mot(['acheter'],'かう',basic_score),
    new Mot(['visage'],'かお',basic_score),
    new Mot(['clé'],'かぎ',basic_score),
    new Mot(['écrire'],'かく',basic_score),
    new Mot(['parapluie'],'かさ',basic_score),
    new Mot(['prêter'],'かす',basic_score),
    new Mot(['vent'],'かぜ',basic_score),
    new Mot(['famille'],'かぞく',basic_score),
    new Mot(['école'],'がっこう',basic_score),
    new Mot(['sac'],'かばん',basic_score),
    new Mot(['papier'],'かみ',basic_score),
    new Mot(['appareil photo'],'カメラ',basic_score),
    new Mot(['mardi'],'かようび ',basic_score),
    new Mot(['épicé'],'からい',basic_score),
    new Mot(['emprunter'],'かりる',basic_score),
    new Mot(['léger'],'かるい',basic_score),
    new Mot(['calendrier'],'カレンダー',basic_score),
    new Mot(['rivière'],'かわ',basic_score),
    new Mot(['mignon'],'かわいい',basic_score),
    new Mot(['arbre'],'き',basic_score),
    new Mot(['jaune'],'きいろい',basic_score),
    new Mot(['écouter'],'きく',basic_score),
    new Mot(['nord'],'きた',basic_score),
    new Mot(['guitare'],'ギター',basic_score),
    new Mot(['sale'],'きたない',basic_score),
    new Mot(['timbre'],'きって',basic_score),
    new Mot(['ticket'],'きっぷ',basic_score),
    new Mot(['hier'],'きのう',basic_score),
    new Mot(['neuf'],'きゅう',basic_score),
    new Mot(['aujourd\'hui'],'きょう',basic_score),
    new Mot(['salle de classe'],'きょうしつ',basic_score),
    new Mot(['année dernière'],'きょねん',basic_score),
    new Mot(['beau'],'きれい',basic_score),
    new Mot(['banque'],'ぎんこう',basic_score),
    new Mot(['vendredi'],'きんようび',basic_score),
    new Mot(['médicament'],'くすり',basic_score),
    new Mot(['fruit'],'くだもの',basic_score),
    new Mot(['bouche', 'ouverture'],'くち',basic_score),
    new Mot(['chaussures'],'くつ',basic_score),
    new Mot(['chaussettes'],'くつした',basic_score),
    new Mot(['pays'],'くに',basic_score),
    new Mot(['voiture', 'automobile'],'くるま',basic_score),
    new Mot(['noir'],'くろい',basic_score),
    new Mot(['ce matin'],'けさ',basic_score),
    new Mot(['mariage'],'けっこん',basic_score),
    new Mot(['entrée', 'vestibule'],'げんかん',basic_score),
    new Mot(['cinq'],'ご',basic_score),
    new Mot(['parc'],'こうえん',basic_score),
    new Mot(['thé noir'],'こうちゃ',basic_score),
    new Mot(['voix'],'こえ',basic_score),
    new Mot(['café'],'コーヒー',basic_score),
    new Mot(['après-midi'],'ごご',basic_score),
    new Mot(['matin'],'ごぜん',basic_score),
    new Mot(['cette année'],'ことし',basic_score),
    new Mot(['mot'],'ことば',basic_score),
    new Mot(['enfant'],'こども',basic_score),
    new Mot(['repas'],'ごはん',basic_score),
    new Mot(['ce mois', 'ce mois-ci'],'こんげつ',basic_score),
    new Mot(['cette semaine'],'こんしゅう',basic_score),
    new Mot(['bonjour'],'こんにちは',basic_score),
    new Mot(['ce soir'],'こんばん',basic_score),
    new Mot(['bonsoir'],'こんばんは',basic_score),
    new Mot(['poisson'],'さかな',basic_score),
    new Mot(['alcool'],'さけ',basic_score),
    new Mot(['magazine', 'revue'],'ざっし',basic_score),
    new Mot(['sucre'],'さとう',basic_score),
    new Mot(['froid'],'さむい',basic_score),
    new Mot(['au revoir'],'さようなら',basic_score),
    new Mot(['assiette'],'さら',basic_score),
    new Mot(['trois', 'monsieur', 'madame'],'さん',basic_score),
    new Mot(['promenade', 'balade'],'さんぽ',basic_score),
    new Mot(['quatre'],'し',basic_score),
    new Mot(['heure'],'じ',basic_score),
    new Mot(['sel'],'しお',basic_score),
    new Mot(['mais', 'cependant'],'しかし',basic_score),
    new Mot(['travail'],'しごと',basic_score),
    new Mot(['dictionnaire'],'じしょ',basic_score),
    new Mot(['calme'],'しずか',basic_score),
    new Mot(['sous', 'dessous', 'en-dessous'],'した',basic_score),
    new Mot(['question'],'しつもん',basic_score),
    new Mot(['vélo', 'bicyclette'],'じてんしゃ',basic_score),
    new Mot(['fermer', 'attacher'],'しめる',basic_score),
    new Mot(['photo', 'photographie'],'しゃしん',basic_score),
    new Mot(['chemise'],'シャツ',basic_score),
    new Mot(['douche'],'シャワー',basic_score),
    new Mot(['cours'],'じゅぎょう',basic_score),
    new Mot(['sauce soja'],'しょうゆ',basic_score),
    new Mot(['savoir'],'しる',basic_score),
    new Mot(['blanc'],'しろい',basic_score),
    new Mot(['journal'],'しんぶん',basic_score),
    new Mot(['mercredi'],'すいようび',basic_score),
    new Mot(['jupe'],'スカート',basic_score),
    new Mot(['immédiatement'],'すぐに',basic_score),
    new Mot(['un peu'],'すこし',basic_score),
    new Mot(['frais'],'すずしい',basic_score),
    new Mot(['cuillère'],'スプーン',basic_score),
    new Mot(['sport'],'スポーツ',basic_score),
    new Mot(['pantalon'],'ズボン',basic_score),
    new Mot(['chaussons','pantoufles'],'スリッパ',basic_score),
    new Mot(['faire'],'する',basic_score),
    new Mot(['s\'asseoir'],'すわる',basic_score),
    new Mot(['pull','sweat'],'セーター',basic_score),
    new Mot(['savon'],'せっけん',basic_score),
    new Mot(['mille'],'せん',basic_score),
    new Mot(['mois dernier'],'せんげつ',basic_score),
    new Mot(['semaine dernière'],'せんしゅう',basic_score),
    new Mot(['maître','professeur','enseignant'],'せんせい',basic_score),
    new Mot(['lessive'],'せんたく',basic_score),
    new Mot(['ensuite','après'],'そうして',basic_score),
    new Mot(['extérieur','dehors'],'そと',basic_score),
    new Mot(['ciel'],'そら',basic_score),
    new Mot(['université'],'だいがく',basic_score),
    new Mot(['ambassade'],'たいしかん',basic_score),
    new Mot(['important'],'たいせつ',basic_score),
    new Mot(['cuisine'],'だいどころ',basic_score),
    new Mot(['haut','élevé','cher'],'たかい',basic_score),
    new Mot(['chat'],'ねこ',basic_score),
    new Mot(['souris'],'ねずみ',basic_score)
]